<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**========================================================================
 * ?                                ABOUT
 * @author         : Isrfil
 * @email          : israfil@cccul.com
 * @repo           : 
 * @createdOn      : 03-10-2022
 * @updatedBy      : Newton Mitro
 * @UpdatedAt      : 15-10-2022
 * @description    : Application stage seeder
 *========================================================================**/

class ServiceCenterSeeder extends Seeder {

    public function run() {
        DB::table('service_centers')->insert([
            'service_center_name'       => 'Head Office',
            'address'                   => 'Rev. Fr. Charles J. Young Bhaban, 173/1/A, East Tejturi Bazar, Tejgaon, Dhaka-1215.',
            'phone_number'              => '02-9123764, 02-9139901-2, 02-58152640, 02-58153316',
            'fax'                       => '88-02-9143079',
            'email'                     => 'info@cccul.com',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);

        DB::table('service_centers')->insert([
            'service_center_name'       => '',
            'address'                   => '',
            'phone_number'              => '',
            'fax'                       => '',
            'email'                     => '',
            'work_days'                 => '',
            'opening_time'              => '',
            'closing_time'              => '',
            'acting_in_charge'          => '',
            'in_charge_designation'     => '',
            'latitude'                  => '',
            'longitude'                 => '',
            'service_center_type_id'    => '',
            "created_at"                => \Carbon\Carbon::now(),
            "updated_at"                => \Carbon\Carbon::now(),
        ]);
    }
}
